name: Build latest Docker image

on:
  schedule:
    # Runs at 11:00 UTC every Monday
    - cron: '0 11 * * 1'
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest published version of this repo
        id: this_repo
        run: |
          VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep \"tag_name\" | awk -F\" '{print substr($4, 2)}')
          echo "Latest published version: $VERSION"
          echo "latest_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest published version upstream
        id: upstream
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep \"tag_name\")
          VERSION=$(echo $LATEST_RELEASE | awk -F\" '{print substr($4, 2)}')
          echo "Extracted version: $VERSION"
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "latest_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if build is necessary
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version
        run: echo "Version differs from the latest published. Proceeding with build."
        
      - name: Checkout
        uses: actions/checkout@v4
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v4
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Create GitHub Release
        if: steps.this_repo.outputs.latest_version != steps.upstream.outputs.latest_version
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.upstream.outputs.latest_version }}
          name: v${{ steps.upstream.outputs.latest_version }}
          body: |
            Automated build of Caddy v${{ steps.upstream.outputs.latest_version }}.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
