name: Build latest Docker image

on:
  schedule:
    # Runs at 11:00 UTC every Monday
    - cron: '0 11 * * 1'
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      build_needed: ${{ steps.check.outputs.build_needed }}
      latest_version: ${{ steps.upstream.outputs.latest_version }}
    steps:
      - name: Get latest published version of this repo
        id: this_repo
        run: |
          VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep \"tag_name\" | awk -F\" '{print substr($4, 2)}')
          echo "Latest published version: $VERSION"
          echo "latest_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest published version upstream
        id: upstream
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep \"tag_name\")
          VERSION=$(echo $LATEST_RELEASE | awk -F\" '{print substr($4, 2)}')
          echo "Extracted version: $VERSION"
          echo "latest_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if build is necessary
        id: check
        run: |
          if [ "${{ steps.this_repo.outputs.latest_version }}" != "${{ steps.upstream.outputs.latest_version }}" ]; then
            echo "Build is necessary"
            echo "build_needed=true" >> $GITHUB_OUTPUT
          else
            echo "Build is not necessary"
            echo "build_needed=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.build_needed == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ needs.check-version.outputs.latest_version }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.latest_version }}
          name: v${{ needs.check-version.outputs.latest_version }}
          body: |
            Automated build of Caddy v${{ needs.check-version.outputs.latest_version }}.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
