# This is a basic workflow to help you get started with Actions

name: Build latest Docker image

on:
  push:
    tags:
      - "*"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ !github.event.act }} # skip during local actions testing

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare tags
        if: success()
        id: prepare
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest)
          VERSION=$(echo $LATEST_RELEASE | grep .tag_name | awk -F\" '{print substr($4, 2)}')
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo "::set-output name=tag::$(echo $VERSION)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
